version: "3.2"
services:
  mysql:
    image: mysql:5.7.26
    container_name: mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=jetbook"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "3306:3306"
  jetbook:
    image: jetbook:latest
    container_name: jetbook
    links:
      - mysql
    environment:
      - MYSQL_PASS=password
      - MYSQL_DBNAME=jetbook
      - MYSQL_ACCESS=tcp(127.0.0.1:3306)
      - MYSQL_HOST=Local
      - MYSQL_USER=root
    ports:
      - "8080:8080"
